name: Create release tag and release note.

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-release-tag:
    # PRがマージされたときのみ実行
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      TZ: "Asia/Tokyo"

    steps:
      - uses: actions/checkout@v4

      # 前回のリリースタグを取得する
      - name: Get previous tag
        id: pre_tag
        run: |
          echo "pre_tag=$(curl -H 'Accept: application/vnd.github.v3+json' -H 'Authorization: token ${{ secrets.GH_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)" >> $GITHUB_OUTPUT

      # タグを生成する 「{YYYY.MM.DD}-{当日リリース回数}」
      - name: Generate tag
        id: release_tag
        run: |
          today=$(date +'%Y.%m.%d')
          pre_release_date=$(echo ${{ steps.pre_tag.outputs.pre_tag }} | awk -F'-' '{print $1}')
          pre_release_count=$(echo ${{ steps.pre_tag.outputs.pre_tag }} | awk -F'-' '{print $2}')
          if [[ ! $pre_release_date = $today ]]; then
            pre_release_count=0
          fi
          echo "release_tag=$today-$(($pre_release_count + 1))" >> $GITHUB_OUTPUT

      # PRのタイトルと番号を取得
      - name: Get pr title and number
        id: pr_title
        run: |
          pr_title=$(curl -H 'Authorization: Bearer ${{ secrets.GH_TOKEN }}' \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number}}" \
            | jq -r '.title')
          pr_number=${{ github.event.pull_request.number }}
          formatted_pr_title="${pr_title} (#${pr_number})"
          echo "formatted_pr_title=${formatted_pr_title}" >> $GITHUB_OUTPUT

      - name: Create release note body
        id: release_note_body
        run: |
          release_note_body="${{ steps.pr_title.outputs.formatted_pr_title }} ${{ steps.changes.outputs.changes }}"
          # 文字列から不要な文字を削除
          release_note_body=$(echo "$release_note_body" | sed 's/\\"//g' | sed 's/["“]//g')
          echo "release_note_body=$release_note_body" >> $GITHUB_OUTPUT

      # タグを切り、リリースノートを作成する
      # PRのラベルに応じてカテゴライズする場合は、使用先のリポジトリで下記を定義する
      # https://docs.github.com/ja/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes
      - name: Create Release
        run: |
          response=$(curl -X POST \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -d "{ \
              \"tag_name\": \"${{ steps.release_tag.outputs.release_tag }}\", \
              \"target_commitish\": \"main\", \
              \"name\": \"${{ steps.release_tag.outputs.release_tag }}\", \
              \"body\": \"${{ steps.release_note_body.outputs.release_note_body }}\" \
            }" \
            -w "%{http_code}" \
            -o response_body.txt \
            https://api.github.com/repos/${{ github.repository }}/releases)
            status_code=$(tail -n1 <<< "$response")
            echo "Status Code: $status_code"
            body=$(cat response_body.txt)
            echo "Response Body: $body"
            if [ $status_code -ne 201 ]; then
              echo "Failed to create release"
              exit 1
            fi
